---
kind: pipeline
name: google-cloud

steps:
- name: check for accidentally dropped creds
  image: yellowmegaman/container-trufflehog:2.0.98
  commands:
  - /usr/local/bin/trufflehog --regex --entropy=False file:///$CI_WORKSPACE

- name: build-gce-image
  image: yellowmegaman/container-packer:1.3.3
  environment:
    GOOGLE_PROJECT:
      from_secret: google_project
    GOOGLE_CREDENTIALS:
      from_secret: google_credentials
  commands:
  - packer build -force -only=gce golden-image.json

---
kind: pipeline
name: aws

steps:
- name: check for accidentally dropped creds
  image: yellowmegaman/container-trufflehog:2.0.98
  commands:
  - /usr/local/bin/trufflehog --regex --entropy=False file:///$CI_WORKSPACE

- name: build-ami
  image: yellowmegaman/container-packer:1.3.3
  environment:
    AWS_ACCESS_KEY:
      from_secret: aws_access_key
    AWS_SECRET_KEY:
      from_secret: aws_secret_key
  commands:
  - packer build -force -only=aws golden-image.json

#---
#kind: pipeline
#name: digitalocean
#
#steps:
#- name: check for accidentally dropped creds
#  image: yellowmegaman/container-trufflehog:2.0.98
#  commands:
#  - /usr/local/bin/trufflehog --regex --entropy=False file:///$CI_WORKSPACE
#
#- name: build-do-image
#  image: yellowmegaman/container-packer:1.3.3
#  environment:
#    DIGITALOCEAN_API_TOKEN:
#      from_secret: do_token
#  commands:
#  - packer build -force -only=do golden-image.json
