name: golden-image-master
on:
  push:
    branches:
      - master
env:
  PACKER_VERSION: 1.5.1
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
jobs:
  terraform:
    name: golden-image-master
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: get packer
        run: |
          wget -q https://releases.hashicorp.com/packer/${{env.PACKER_VERSION}}/packer_${{env.PACKER_VERSION}}_linux_amd64.zip
          unzip -q packer_${{env.PACKER_VERSION}}_linux_amd64.zip
          rm packer_${{env.PACKER_VERSION}}_linux_amd64.zip
      - name: create aws image
        run: $GITHUB_WORKSPACE/packer build -force -only=aws golden-image.json
